# Definição dos cenários
image bg room = "images/cenarios/room.jpg"
image bg city = "images/cenarios/city.png"
image bg cinema = "images/cenarios/cinema.png"
image bg cinema_katia_samantha = "images/cenarios/scene/cinema_katia_samantha.png"
image bg cinema_exhibition = "images/cenarios/scene/amostra_filmes_katia_samantha.png"
image bg cinema_cafe = "images/cenarios/scene/cinema_lobby.png"
image bg cinema_cafeteria = "images/cenarios/Cafeteria.png"
image bg cinema_lobby_empty = "images/cenarios/cinema_lobby.png"
image bg cinema_arcade = "images/cenarios/Arcade.jpg"
image bg quadra_volei = "images/cenarios/QUADRA.png"
image bg cafeteria = "images/cenarios/Cafeteria.png"
image bg art_room = "images/cenarios/art_room.png"
# Adicione outros cenários conforme necessário
# image bg park = "images/cenarios/park.jpg"